version: 1
formatters:
  simple:
    format: '%(asctime)s | %(name)s | %(levelname)s | %(threadName)s | process-%(process)d | %(message)s'
  debug:
    format: '%(asctime)s | %(name)s | %(levelname)s | %(threadName)s | process-%(process)d | %(pathname)s - %(funcName)s - %(lineno)d | %(message)s'
handlers:
  serv:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  servDev:
    class: logging.StreamHandler
    level: DEBUG
    formatter: debug
    stream: ext://sys.stdout
loggers:
  serverDev:
    level: DEBUG
    handlers: [servDev]
    propagate: no
  server:
    level: INFO
    handlers: [serv]
    propagate: no
root:
  level: DEBUG
  handlers: [serv]
